### ISSUE TITLE
Проблема с VK в урл

### ISSUE THREAD

**Issue by TITAN-UZ** [bezumkin/modx-hybridauth#33]
Приветь
Не могу настроит авторизацию через vk
id и secret указал в настройках но при выполнения скрипта в урл вместо моего id показывает 12345

https://oauth.vk.com/authorize?client_id=12345&

Если вместо 12345 поставит мой id то без проблем работает 

На базе все показывает правилно

**Comment by bezumkin** [comment]
Такое может быть если старый кэш или параметр указан с ошибкой (ломается JSON).

Компонент проверен много-много раз. В частности, авторизация через VK работает на https://id.modx.pro
