### ISSUE TITLE
Wrong Facebook permissions

### ISSUE THREAD

**Issue by PatchRanger** [bezumkin/modx-hybridauth#34]
## How to reproduce?
Follow the installation instructions as in http://docs.modx.pro/components/hybridauth/providers/facebook .
Try to login via Facebook.

## Expected result
Successful login.

## Real result
I see such Facebook message:
> Invalid Scopes: read_stream, read_friendlists. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

I am going to provide a pull-request, replacing those permissions to correct ones.

**Comment by bezumkin** [comment]
Try provide this to https://github.com/hybridauth/hybridauth/issues

**Comment by PatchRanger** [comment]
That helped: https://github.com/hybridauth/hybridauth/issues/280#issuecomment-68483500
